thermal_disable=0
battery_spoof_enable=0
battery_spoof_temp=25
thermal_prediction_enable=1
thread_pin_enable=1
boot_delay=8
debug=0
lru_gen_enable=1
cpu_hotplug_enable=0
net_qos_enable=1
adaptive_thermal=1
wifi_ps_disable=1
